name: shop
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.2.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.3
  # firebase_storage: ^11.5.3
  google_sign_in: ^6.1.6
  # image_picker: ^1.0.4
  uuid: ^4.2.1
  permission_handler: ^11.0.0
  provider: ^6.0.5
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  http: ^1.1.0
  razorpay_flutter: ^1.4.0
  video_player: ^2.8.5
  chewie: ^1.7.5
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^18.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/appicon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
